### ISSUE TITLE
Example not working.

### ISSUE THREAD

**Issue by juliofalbo** [Azure-Samples/cosmos-dotnet-change-feed-processor#5]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Just clone to project, change the ConnectionString in `appsettings.json` and try to run.

### Any log messages given by the failure
> `Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'Missing 'ConnectionString' setting in configuration.')`

### Expected/desired behavior
> Working

### OS and Version?
> macOS Catalina

### Versions
> 10.15.6

**Comment by ealsur** [comment]
It's fixed in the current repo state, thanks for reporting
