### ISSUE TITLE
Where to host Change feed processor in Azure Cosmos DB?

### ISSUE THREAD

**Issue by sagarkul** [Azure-Samples/cosmos-dotnet-change-feed-processor#6]
Can we use Azure function app to host feed processor?
Any other Azure service to host this?

**Comment by ealsur** [comment]
See https://docs.microsoft.com/en-us/azure/cosmos-db/sql/change-feed-processor#where-to-host-the-change-feed-processor

**Comment by sagarkul** [comment]
I don't want to use hosted service or web job. can I use a simple function app instead?

**Comment by ealsur** [comment]
If you want to use a Function App you can sure, but if you are using Functions, just use the Azure Functions Cosmos DB Trigger: 

* https://docs.microsoft.com/en-us/azure/cosmos-db/sql/change-feed-functions
* https://docs.microsoft.com/en-us/azure/cosmos-db/sql/read-change-feed#azure-functions
* https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?tabs=csharp

You don't need to create a Change Feed Processor for that.
